name: "Shared steps for live testing jobs"
description: "Shared steps for live testing jobs"
runs:
  using: "composite"
  steps:
    - name: Wait for Mina Network readiness
      uses: o1-labs/wait-for-mina-network-action@v1
      with:
        mina-graphql-port: 8080
        max-attempts: 60
        polling-interval-ms: 10000
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Build SnarkyJS and Execute Tests
      env:
        TEST_TYPE: "Live integration tests"
        USE_LOCAL_NETWORK: "true"
      continue-on-error: false
      run: |
        git submodule update --init --recursive
        npm ci
        npm run build:node
        touch profiling.md
        sh run-ci-tests.sh
        cat profiling.md >> $GITHUB_STEP_SUMMARY
      shell: bash
