name: Build SnarkyJS
on:
  push:
    branches:
      - main
      - releases
  pull_request:
    branches:
      - main
      - releases

jobs:
  Build-And-Test-Server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build SnarkyJS and Execute Tests
        run: |
          npm ci
          npm run build:node
          npm run test:unit
          npm run test
          npm run test:integration
      - name: Publish to NPM if version has changed
        uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/heads/releases'
        with:
          token: ${{ secrets.NPM_TOKEN }}
        env:
          INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}

  Build-And-Test-Web:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Node Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npm run e2e:install
      - name: Build SnarkyJS and Prepare the Web Server
        run: |
          npm run clean
          npm run build:web
          npm run build:examples
          npm run e2e:prepare-server
      - name: Run Web Server
        run: python dist/web/server.py &
      - name: Execute E2E Tests
        run: npm run test:e2e
      - name: Upload E2E Test Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: e2e-tests-report
          path: tests/report/
          retention-days: 30
